### PR TITLE
Add Argentinian Peso (ARS) currency

### PR DESCRIPTION
**Pull request by nicooga**
Add ARS currency.

### CODE REVIEW

**Comment by theocodes** [comment]
Thanks for this @nicooga! 👍  

Would mind changing it so it stays in alphabetical order please?

Thanks!

**Comment by theocodes** [comment]
@nicooga ping :)

**Comment by nicooga** [comment]
@theocodes done, sorry for the delay.

I think it's probably a good idea to provide people to add currencies via config. Having to fork and optionally fire a PR to have your custom currency is not user friendly at all.

**Comment by theocodes** [comment]
@nicooga thanks for that! :+1: 

I see your point above and will take it into consideration.. I wouldn't want to ship with no predefined currencies, but perhaps allowing for custom currencies via configuration isn't a bad approach.

This approach is bound to bring up other challenges as well which I need to have a think about. In the mean time is allows for contributions which is great since there's still a lot of people learning elixir and wanting to get the feet wet :smile:

**Pull request merged**
